### ISSUE TITLE
Qualweb stalling

### ISSUE THREAD

**Issue by geirsf** [qualweb/core#11]
Qualweb seems to "stall" when trying to evaluate https://www.komplett.no

**Version of QW:** 0.4.33
**URL tested**:  https://www.komplett.no
**Issue**:  Qualweb "stalls" with no error-messages. Never finishes the evaluation. 
**Rules running"**:  Only ACT-rules at level A and AA

**Comment by carlosapaduarte** [comment]
Hi @geirsf 

Thanks for reporting this. Problem has been fixed in version 0.4.34

**Comment by geirsf** [comment]
@carlosapaduarte   I tried to use version 0.4.35 to verify, but it stared complaining about 
nnot find module Error: Cannot find module '@qualweb/wappalyzer', even thow it's sets to false in the evaluationOptions:

  const evaluationOptions = {
            "url": url,
            "execute": { // choose which modules to execute
                "wappalyzer": false, // wappalyzer module (https://github.com/qualweb/wappalyzer) - default value = false
                "act": true, // act-rules module (https://github.com/qualweb/act-rules) - default value = true
                "html": false, // html-techniques module (https://github.com/qualweb/html-techniques) - default value = true
                "css": false, // css-rules module (https://github.com/qualweb/css-techniques) - default value = true
                "bp": false // best-practices module (https://github.com/qualweb/best-practices) - default value = true
            },
            "act-rules": { // More information about this options at https://github.com/qualweb/act-rules
                "levels": ["A","AA"] // Conformance levels to execute, 
            },
        };

Has something in the config-options changed?

**Comment by carlosapaduarte** [comment]
Sorry about that. We need to check what triggered that. We're seeing it also.
You can bypass the issue by installing the module manually (the issue is that the module stopped being installed automatically). Just do
```
npm install @qualweb/wappalyzer 
```

**Comment by geirsf** [comment]
I see. Tried to install qualweb/wappalyzer 0.2.0 manually but it gives the following error:

undefined:10415
          text: ""
          ^

SyntaxError: Unexpected token t in JSON at position 281348
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (C:\Users\gsf\source\repos\Qualweb-server\Qualweb-server\node_modules\wappalyzer\driver.js:47:43)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (C:\Users\gsf\source\repos\Qualweb-server\Qualweb-server\node_modules\@qualweb\wappalyzer\dist\index.js:7:38)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)

**Comment by joao-vicente** [comment]
I've update @qualweb/core to version 0.4.37. Can you test again and check if the problem persists?

**Comment by geirsf** [comment]
Works fine as of QW-core  0.4.41
