### ISSUE TITLE
False negative on "First focusable element is link to non-repeated content" test

### ISSUE THREAD

**Issue by iamfrank** [qualweb/core#17]
Hi there

I'm scanning pages using `@qualweb/core 0.5.4` with `@qualweb/act-rules 0.5.3` and consistently getting this result:

Scanning `https://webaim.org/techniques/skipnav/` produces 0 fails.
Scanning `https://webaim.org/techniques/skipnav/#alternatives` produces 1 fail.

When the scan fails, it fails on "First focusable element is link to non-repeated content". 
I suppose the deep link that focuses the page in the "alternatives" section at page load makes qualweb think that the page starts here.
```
{
                        "@type": "Assertion",
                        "test": {
                            "@id": "https://act-rules.github.io/rules/8a213c",
                            "@type": "TestCase",
                            "title": "First focusable element is link to non-repeated content",
                            "description": "This rule checks that the first focusable element is a link to non-repeated content in the page"
                        },
                        "mode": "earl:automatic",
                        "result": {
                            "@type": "TestResult",
                            "outcome": "earl:failed",
                            "source": [
                                {
                                    "result": {
                                        "pointer": "html > body:nth-child(2) > main:nth-child(2) > aside:nth-child(2) > div:nth-child(2) > ul:nth-child(2) > li:nth-child(1) > a:nth-child(1)",
                                        "outcome": "earl:failed"
                                    }
                                }
                            ],
                            "description": "The first focusable element does not skip to the main content",
                            "date": "2021-04-14 10:31:44"
                        }
                    },
```

**Comment by carlosapaduarte** [comment]
Hey @iamfrank 

This is quite an interesting find! What we do to test that rule is "press" the tab key and check what element gains focus (similar to what you would do to manually test it). 

With the first URL the tab takes you to the skip link. With the second URL it doesn't (it takes you to the German translation link), therefore the rule fails.

But having the navigation anchor in the URL should not change what the page is, so I guess we need to take that out of the page that we want to load. Look for a fix in the coming versions!

Thanks!

**Comment by iamfrank** [comment]
You're welcome
