### ISSUE TITLE
Error when logging errors to file

### ISSUE THREAD

**Issue by nippoolg** [qualweb/core#18]
I'm running Qualweb core in Azure function environment. Version 0.5.7 worked perfectly. Now when trying to update to 0.7.2 getting error: 
Error: EROFS: read-only file system, open '/home/site/wwwroot/qualweb-errors-1627900535378.log'], Error: EROFS: read-only file system, unlink '/home/site/wwwroot/qualweb-errors-1627900535378.log
Is there any chance to have option to log evaluation errors into console, not the log file?

**Comment by joao-vicente** [comment]
Hi @nippoolg, i've just realease a patch. Can you try again to see if you still have the same problem?

**Comment by nippoolg** [comment]
That works perfectly, sorry I didn't remember to confirm that.
