### ISSUE TITLE
Interacting (login) page before evaluation

### ISSUE THREAD

**Issue by SavvasKatsuyaSawada** [qualweb/core#19]
Hello
I would like to evaluate website which requires 'login', but I couldn't find a way before evaluating target URL(s).
Is there nice way to interact puppeteer's page within qualweb.evaluate method, so that I can write steps to interact login page?

**Comment by joao-vicente** [comment]
Hi @SavvasKatsuyaSawada, currently there's no way to evaluate pages behind a login page through @qualeb/core. We have been planning to implement this feature, and it's on our roadmap, but we don't have any set date for when it will happen.

For now if you really want to evaluate such pages you can use [qualweb chrome extension](https://chrome.google.com/webstore/detail/qualweb-extension/ljgilomdnehokancdcbkmbndkkiggioc).
