### ISSUE TITLE
Example in readme doesn't work

### ISSUE THREAD

**Issue by Tellus** [qualweb/core#2]
Hi!

The code example in README.md doesn't seem to work properly. Firstly (and trivially), the constant `earlReports` is declared, but the name `earlReport` is used later. Secondly, both `evaluate()` and `generateEarlReport()` yield empty objects when run.

I dug into the code and saw that if the internal `System` instance has *not* been initialized with `start()`, then `evaluate()` will not yield any results.

Using the `start()` and `close()` functions exposed by @qualweb/core fixed the problem.

I've written a quick change in a local fork (22e0968f363ed5f7a7c5fcc829d6a255d47bb28f). I can submit a pull request if the change is in line with your coding style and intended API usage.

**Comment by joao-vicente** [comment]
Hi, thank you for pointing that out! 

Sometimes when i update the code, i forget to update the README.md. I already have that task in my to do list since we also have other packages README.md outdated.

I'll update all in the next few days!
