### ISSUE TITLE
Can't get qualweb working with viewport "mobile" option

### ISSUE THREAD

**Issue by nippoolg** [qualweb/core#21]
I'm trying to get evaluation with viewport "mobile" option, but evaluation fails in any case. 
Qualweb options as follows:
{"urls":["https://..."],"log":{"console":true},"viewport":{"mobile":true,"landscape":false},"execute":{"act":true,"wcag":false},"act-rules":{"levels":["A","AA"]}}

Got error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'validateZoomedTextNodeNotClippedWithCSSOverflow')
[2022-02-17T07:26:01.577Z]     at __puppeteer_evaluation_script__:2:28

Tried to update Qualweb and puppeteer versions as well, but nothing changed.
 "@qualweb/core": "^0.7.18",
    "puppeteer": "^13.1.3"

Running code on Azure Function Environment. Any ideas what's going wrong?

**Comment by nippoolg** [comment]
Yes, that works now! Thanks! Can I ask one more question: is there a way to test mobile viewport with qualweb-extension?

**Comment by carlosapaduarte** [comment]
Have you tried changing the device to a mobile device in Chrome Desktop and then running the extension?

**Comment by nippoolg** [comment]
Yes, I can change device through DevTools and run evaluation. In the report we get from qualweb-extension there is no mention about viewport used, that's why I'm not sure if it is testing in mobile viewport actually or not.
