### ISSUE TITLE
Qualweb crashes on website

### ISSUE THREAD

**Issue by Tellus** [qualweb/core#24]
Hey guys,

We're starting up our first batch of the year, and Qualweb is working great on most sites. We've hit one, however, that just causes it to crash. Your online evaluator also seems to have issues with the page.

The following URLs on plejecenterortved.ringsted.dk have been causing issues:

- https://plejecenterortved.ringsted.dk/borger/omsorg-sundhed/boligerne
- https://plejecenterortved.ringsted.dk/borger/omsorg-sundhed/mad

Several others on the domain seem to be working fine. A few examples:
- https://plejecenterortved.ringsted.dk/
- https://plejecenterortved.ringsted.dk/borger/omsorg-sundhed/om-plejecenter-ortved
- https://plejecenterortved.ringsted.dk/aktiviteter-1

I'm not getting any real trace logs, so I'm afraid I can't send you a debug log / stacktrace :-/

**Comment by carlosapaduarte** [comment]
Hi @Tellus 

We are not able to load any of the webpages you mentioned (not only the ones QualWeb was not able to evaluate). And by load, I mean loading them in a standard browser, not on QualWeb. Can you confirm that you are able to load these pages?

**Comment by Tellus** [comment]
Hi @carlosapaduarte - thanks for responding so quickly.

The sites still load just fine for us. Then I tried via VPN connecting through Portugal, and the site refuses to load. Looks like they have some sort of geoblock in place (probably because it's only meant to be used by Danish citizens).

I don't know if you have access to a VPN service that lets you route through Denmark (I think TunnelBear VPN has a free tier with Danish servers) or if you have a few debugging tips I could try out for some local diagnostics.

**Comment by carlosapaduarte** [comment]
Hi @Tellus 

We've tried with the VPN and we were able to evaluate all the pages you mentioned.
Can you tell us what are the versions of the QualWeb componentes you are using?
