### ISSUE TITLE
Consider switching to a monorepo

### ISSUE THREAD

**Issue by not-my-profile** [qualweb/core#26]
The source code of QualWeb is currently split across ~16 repositories:

* https://github.com/qualweb/cli
* https://github.com/qualweb/core
* https://github.com/qualweb/crawler
* https://github.com/qualweb/dom
* https://github.com/qualweb/earl-reporter
* https://github.com/qualweb/evaluation
* https://github.com/qualweb/locale
* https://github.com/qualweb/qw-element
* https://github.com/qualweb/qw-page
* https://github.com/qualweb/types
* https://github.com/qualweb/util
* https://github.com/qualweb/wcag-techniques
* executable modules
    * https://github.com/qualweb/act-rules
    * https://github.com/qualweb/best-practices
    * https://github.com/qualweb/counter
    * https://github.com/qualweb/wcag-techniques
    * https://github.com/qualweb/wappalyzer

This makes contributing to QualWeb quite cumbersome: you firstly need to find the right repository, then fork it, clone it, etc. But even more importantly it makes refactors that span multiple repositories very cumbersome because you'd need to open several PRs for them. For instance I'd like to contribute a `noHtml` option ([like axe has it](https://www.deque.com/axe/core-documentation/api-documentation/#user-content-api-name-axeconfigure)) to exclude the `html` and `htmlCode` fields from the generated reports (since for large pages including the HTML can make the reports very large). However this would currently require me to make ~5 PRs [across the various repositories](https://github.com/search?l=TypeScript&p=1&q=org%3Aqualweb+htmlcode&type=Code).

These various modules are all quite tightly interdependent, so I really think a mono-repo would be much more preferable. For example see the [axe-core-npm](https://github.com/dequelabs/axe-core-npm) repository, [which contains seven packages](https://github.com/dequelabs/axe-core-npm/tree/develop/packages).

I think the repository merge could be achieved by:

1. Merging the repositories locally while preserving their git histories by firstly rewriting the histories with `git filter-repo --to-subdirectory-filter packages/$name` and then merging them with `git merge --allow-unrelated-histories`. (It might be worth considering grouping the executable modules in a directory.)
2. Publishing the new repository under e.g. https://github.com/qualweb/qualweb.
3. Creating a followup commit in the new repository to update all the URLs in the `package.json` files accordingly.
4. Moving all the existing issues to the new repository.
5. Archiving all the repositories that have been subsumed by the monorepo.

What do you think about this idea? I think it would really make QualWeb more accessible to contributors and open the door to some valuable cross-cutting contributions that would otherwise be very cumbersome to implement (for instance currently none of the repositories have CI set up, setting it up once would be easy but setting it up 16 times would be cumbersome). I'd be happy to help with this endeavor :)

**Comment by Tellus** [comment]
Great write-up! I only just saw this issue, so apologies for a late comment.

I asked about this informally a year or two ago (even took a very early stab at it using the same steps you suggested: https://github.com/Tellus/qualweb). Back then I think the major issue was making it easier for their students to make focused contributions without risking complications between modules. This is still easily avoided in monorepos, IIRC simpler git repos just fully eliminated the risk in case the students weren't comfortable with git.

Anyway, I'd absolutely support this change as well. Add some CI/semantic-release and I think the code could only be better for it :)

**Comment by AntonioEstriga** [comment]
Hi!
I'm happy to report that this is change is currently in progress at https://github.com/qualweb/qualweb.
