### ISSUE TITLE
BestPractices not defined

### ISSUE THREAD

**Issue by jrpool** [qualweb/core#29]
Any attempt to run qualweb/core with best practices produces this error message:

`undefined : Evaluation failed: ReferenceError: BestPractices is not defined
    at __puppeteer_evaluation_script__:2:24
`
The error is thrown on line 160 of evaliation/dist/index.js:

`const bp = new BestPractices(JSON.parse(locale), options);`

**Comment by AntonioEstriga** [comment]
Hi!
It's working in the current version of the code. For new issues please report them in the monorepo https://github.com/qualweb/qualweb.
