### ISSUE TITLE
Evaluation crashes on specific URL

### ISSUE THREAD

**Issue by Tellus** [qualweb/core#9]
Hey guys,

I've been pitching our backend against a number of more or less random sites, using Qualweb for the underlying evaluation. Most of the time, excellent results!

I've hit one specific URL that seems to crash in Dom.getDOM() when running an evaluation through @qualweb/core. I'm not sure if you'd rather have the issue on @qualweb/dom - let me know if so.

The URL in question is https://www.odense.dk/borger/sundhed-og-sygdom/covid-19-%28corona-virus%29

To reproduce, it should be enough to run a regular Qualweb evaluation on the URL. Our code crashes almost instantly (right after a fetch step). If it helps diagnostics, I'm only running the ACT rules module, levels A and AA.

A secondary big issue is that when this exception occurs, it crashes our Node process - for some reason, we just can't catch the error when it occurs, and so the entire thing goes down. That makes it harder to automate the process - we can't recover if the process straight out crashes :D

Let me know if I can help with any more diagnostic information or similar!

**Comment by joao-vicente** [comment]
Hi, can you tell us which version did you use (or are using)?
We ran that URL with the current version (0.4.19) and it works fine on our system.

Now, the part that makes the Node process to crash, without the possibility to catch it, is definitely a big problem... :(
We'll look into that!

Thanks!

**Comment by Tellus** [comment]
Apologies for the very late reply!

No, we haven't seen anything since 0.4.19 - it seemed to be connected to an HTTP request to one of your servers. Hasn't appeared since.
